{{- if .Values.agent.flow.statefulset.secret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "grafana-agent.fullname" . }}-flow-statefulset
  labels:
    {{- include "grafana-agent.labels" . | nindent 4 }}
    agent-type: statefulset
    mode: flow
data:
  {{- range $key, $val := .Values.agent.flow.statefulset.secret.content }}
  {{ $key }}: {{ $val | b64enc | quote }}
  {{- end }}
{{- end }}
