{{- if not .Values.existingSecret.name -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "prometheus-nosql-exporter.fullname" . }}
  namespace: {{ template "prometheus-nosql-exporter.namespace" . }}
  labels:
    {{- include "prometheus-nosql-exporter.labels" . | nindent 4 }}
type: Opaque
data:
  mongodb-uri: {{ required "A MongoDB URI is required" .Values.nosql.uri | b64enc }}
{{- end -}}
