apiVersion: v1
kind: Service
metadata:
  name: {{ include "prometheus-nosql-exporter.fullname" . }}
  namespace: {{ template "prometheus-nosql-exporter.namespace" . }}
  labels:
    {{- include "prometheus-nosql-exporter.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "prometheus-nosql-exporter.selectorLabels" . | nindent 4 }}
