{{- if .Values.secretStore.enabled }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: elasticsearch
spec:
  provider: {{ .Values.secretStore.platform }}
  secretObjects:
  - secretName: elasticsearch
    type: Opaque
    data:
    - objectName: elasticsearch-credentials
      key: ELASTIC_PASSWORD
  parameters:
{{- if eq .Values.secretStore.platform "azure" }}
    usePodIdentity: "true"
    useVMManagedIdentity: "false"
    userAssignedIdentityID: ""
    keyvaultName: {{ .Values.secretStore.azure.keyvault }}
    cloudName: AzurePublicCloud
    resourceGroup: {{ .Values.secretStore.azure.resourceGroup }}
    subscriptionId: {{ .Values.secretStore.azure.subcription }}
    tenantId: {{ .Values.secretStore.azure.tenant }}
    objects:  |
      array:
        - |
          objectName: elasticsearch-credentials
          objectType: secret
          objectVersion: ""
{{- end }}
{{- end }}
