{{- if .Values.mimirRemoteWrite.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "kube-prometheus-stack.fullname" . }}-mimir-auth-secret
  namespace: {{ template "kube-prometheus-stack.namespace" . }}
  labels:
    app: {{ template "kube-prometheus-stack.name" . }}-mimir-auth-secret
{{ include "kube-prometheus-stack.labels" . | indent 4 }}
data:
  username: {{ default "eAdHuBy6V2P4kuE4" .Values.mimirRemoteWrite.gatewayAuthentication.username | b64enc | quote }}
  password: {{ default "sJCF9tTcHKzJWxYFefbs8M4vtZKwRd2X" .Values.mimirRemoteWrite.gatewayAuthentication.password | b64enc | quote }}
type: Opaque
{{- end }}
