{{- if .Values.agent.flow.deployment.configMap.create }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "grafana-agent.fullname" . }}-flow-deployment
  labels:
    {{- include "grafana-agent.labels" . | nindent 4 }}
    agent-type: deployment
    mode: flow
data:
  {{- if .Values.agent.flow.deployment.configMap.content }}
  config.river: |- {{- (tpl  .Values.agent.flow.deployment.configMap.content .) | nindent 4 }}
  {{- else }}
  config.river: |- {{- .Files.Get "config/config.river" | trim | nindent 4 }}
  {{- end }}
{{- end }}
