---
apiVersion: v1
kind: Secret
metadata:
  name: observability-grafana-agent-static-statefulset
  labels:
    agent-type: statefulset
    mode: static
data:
  snmp.yaml: |-
    auths:
      public_v3:
        security_level: authPriv
        username: snmp_user
        password: snmp_password
        auth_protocol: MD5
        priv_protocol: DES
        priv_password: snmp_password
        version: 3
    modules:
      ribbon_sbc:
        walk:
        - 1.3.6.1.4.1.2879.2.8.5.1.20.1.6
        - 1.3.6.1.4.1.2879.2.8.5.1.20.1.8
        - 1.3.6.1.4.1.2879.2.8.5.1.57.1.4
        - 1.3.6.1.4.1.2879.2.8.5.1.57.1.5
        - 1.3.6.1.4.1.2879.2.8.15.1.2.1.3
        - 1.3.6.1.4.1.2879.2.8.5.1.17.1.3
        - 1.3.6.1.4.1.2879.2.8.5.1.17.1.4
        get:
        - 1.3.6.1.4.1.2879.2.8.5.1.12.1.7.5.118.115.98.99.49
        - 1.3.6.1.4.1.2879.2.8.5.1.12.1.8.5.118.115.98.99.49
        - 1.3.6.1.4.1.2879.2.8.5.1.12.1.9.5.118.115.98.99.49
        - 1.3.6.1.4.1.2879.2.8.5.1.12.1.10.5.118.115.98.99.49
        - 1.3.6.1.4.1.2879.2.8.5.1.12.1.14.5.118.115.98.99.49
        - 1.3.6.1.4.1.2879.2.8.5.1.19.1.2.15.76.88.80.68.69.86.65.90.85.82.69.83.66.67.49
        - 1.3.6.1.4.1.2879.2.8.5.1.19.1.5.15.76.88.80.68.69.86.65.90.85.82.69.83.66.67.49
        - 1.3.6.1.4.1.2879.2.8.5.1.19.1.6.15.76.88.80.68.69.86.65.90.85.82.69.83.66.67.49
        - 1.3.6.1.4.1.2879.2.8.5.6.4.1.8.0
        - 1.3.6.1.4.1.2879.2.8.5.6.4.1.15.0
        - 1.3.6.1.4.1.2879.2.8.5.3.3.1.5.10.118.115.98.99.83.121.115.116.101.109
        - 1.3.6.1.4.1.2879.2.8.5.3.3.1.6.10.118.115.98.99.83.121.115.116.101.109
        - 1.3.6.1.4.1.2879.2.8.5.3.3.1.44.10.118.115.98.99.83.121.115.116.101.109
        - 1.3.6.1.4.1.2879.2.8.5.3.3.1.43.10.118.115.98.99.83.121.115.116.101.109
        - 1.3.6.1.4.1.2879.2.8.5.3.3.1.44.10.118.115.98.99.83.121.115.116.101.109
        metrics:
        - name: sonusSystemServerStatusApplicationVersion
          oid: 1.3.6.1.4.1.2879.2.8.5.1.12.1.7
          type: DisplayString
          help: Indicates the application version currently running on server. - 1.3.6.1.4.1.2879.2.8.5.1.12.1.7
          indexes:
          - labelname: sonusSystemServerStatusName
            type: DisplayString
        - name: sonusSystemServerStatusMgmtRedundancyRole
          oid: 1.3.6.1.4.1.2879.2.8.5.1.12.1.8
          type: gauge
          help: Indicates the redundancy role of the server (for management entities)
            - 1.3.6.1.4.1.2879.2.8.5.1.12.1.8
          indexes:
          - labelname: sonusSystemServerStatusName
            type: DisplayString
          enum_values:
            1: unknown
            2: standby
            3: active
            4: switchoverPending
        - name: sonusSystemServerStatusUpTime
          oid: 1.3.6.1.4.1.2879.2.8.5.1.12.1.9
          type: DisplayString
          help: Indicates the server module uptime in days/hours/minutes/sec. - 1.3.6.1.4.1.2879.2.8.5.1.12.1.9
          indexes:
          - labelname: sonusSystemServerStatusName
            type: DisplayString
        - name: sonusSystemServerStatusApplicationUpTime
          oid: 1.3.6.1.4.1.2879.2.8.5.1.12.1.10
          type: DisplayString
          help: Indicates the application uptime on the server in days/hours/minutes/sec.
            - 1.3.6.1.4.1.2879.2.8.5.1.12.1.10
          indexes:
          - labelname: sonusSystemServerStatusName
            type: DisplayString
        - name: sonusSystemServerStatusCurrentTime
          oid: 1.3.6.1.4.1.2879.2.8.5.1.12.1.14
          type: DisplayString
          help: Indicates the current system time. - 1.3.6.1.4.1.2879.2.8.5.1.12.1.14
          indexes:
          - labelname: sonusSystemServerStatusName
            type: DisplayString
        - name: sonusSystemMemoryUtilCurrentStatisticsAverage
          oid: 1.3.6.1.4.1.2879.2.8.5.1.19.1.2
          type: gauge
          help: The average memory % utilization for this interval. - 1.3.6.1.4.1.2879.2.8.5.1.19.1.2
          indexes:
          - labelname: sonusSystemMemoryUtilCurrentStatisticsCeName
            type: DisplayString
        - name: sonusSystemMemoryUtilCurrentStatisticsAverageSwap
          oid: 1.3.6.1.4.1.2879.2.8.5.1.19.1.5
          type: gauge
          help: The average swap % memory utilization for this interval. - 1.3.6.1.4.1.2879.2.8.5.1.19.1.5
          indexes:
          - labelname: sonusSystemMemoryUtilCurrentStatisticsCeName
            type: DisplayString
        - name: sonusSystemMemoryUtilCurrentStatisticsHighSwap
          oid: 1.3.6.1.4.1.2879.2.8.5.1.19.1.6
          type: gauge
          help: The high swap % memory utilization for this interval. - 1.3.6.1.4.1.2879.2.8.5.1.19.1.6
          indexes:
          - labelname: sonusSystemMemoryUtilCurrentStatisticsCeName
            type: DisplayString
        - name: sonusSystemMemoryUtilIntervalStatisticsHigh
          oid: 1.3.6.1.4.1.2879.2.8.5.1.20.1.6
          type: gauge
          help: The high memory % utilization for this interval. - 1.3.6.1.4.1.2879.2.8.5.1.20.1.6
          indexes:
          - labelname: sonusSystemMemoryUtilIntervalStatisticsNumber
            type: gauge
          - labelname: sonusSystemMemoryUtilIntervalStatisticsCeName
            type: DisplayString
        - name: sonusSystemMemoryUtilIntervalStatisticsAverageSwap
          oid: 1.3.6.1.4.1.2879.2.8.5.1.20.1.8
          type: gauge
          help: The average swap memory % utilization for this interval. - 1.3.6.1.4.1.2879.2.8.5.1.20.1.8
          indexes:
          - labelname: sonusSystemMemoryUtilIntervalStatisticsNumber
            type: gauge
          - labelname: sonusSystemMemoryUtilIntervalStatisticsCeName
            type: DisplayString
        - name: sonusSystemLicenseNodeLockedBundleInfoExpirationDate
          oid: 1.3.6.1.4.1.2879.2.8.5.1.57.1.4
          type: DisplayString
          help: The expiration date for this license - 1.3.6.1.4.1.2879.2.8.5.1.57.1.4
          indexes:
          - labelname: sonusSystemLicenseNodeLockedBundleInfoBundleName
            type: DisplayString
          - labelname: sonusSystemLicenseNodeLockedBundleInfoFeatureName
            type: DisplayString
        - name: sonusSystemLicenseNodeLockedBundleInfoUsageLimit
          oid: 1.3.6.1.4.1.2879.2.8.5.1.57.1.5
          type: gauge
          help: The count provisioned in this license - 1.3.6.1.4.1.2879.2.8.5.1.57.1.5
          indexes:
          - labelname: sonusSystemLicenseNodeLockedBundleInfoBundleName
            type: DisplayString
          - labelname: sonusSystemLicenseNodeLockedBundleInfoFeatureName
            type: DisplayString
        - name: sonusSystemNetworkProcessorStatisticsRtcpGenStatisticsTotalScheduled
          oid: 1.3.6.1.4.1.2879.2.8.5.6.4.1.8
          type: counter
          help: Total RTCP pkts scheduled - 1.3.6.1.4.1.2879.2.8.5.6.4.1.8
          indexes:
          - labelname: sonusSystemNetworkProcessorStatisticsRtcpGenStatisticsNpId
            type: gauge
        - name: sonusSystemNetworkProcessorStatisticsRtcpGenStatisticsTimerCancelFailCnt
          oid: 1.3.6.1.4.1.2879.2.8.5.6.4.1.15
          type: counter
          help: Total failure count of cancelling timer bucket - 1.3.6.1.4.1.2879.2.8.5.6.4.1.15
          indexes:
          - labelname: sonusSystemNetworkProcessorStatisticsRtcpGenStatisticsNpId
            type: gauge
        - name: sonusSystemDspStatusDspUsageG711Total
          oid: 1.3.6.1.4.1.2879.2.8.5.3.3.1.5
          type: gauge
          help: Total G711 resource capacity on this server. - 1.3.6.1.4.1.2879.2.8.5.3.3.1.5
          indexes:
          - labelname: sonusSystemDspStatusDspUsageSystemName
            type: DisplayString
        - name: sonusSystemDspStatusDspUsageG711Utilization
          oid: 1.3.6.1.4.1.2879.2.8.5.3.3.1.6
          type: gauge
          help: Percentage utilization of G711 resources on this server. - 1.3.6.1.4.1.2879.2.8.5.3.3.1.6
          indexes:
          - labelname: sonusSystemDspStatusDspUsageSystemName
            type: DisplayString
        - name: sonusSystemDspStatusDspUsageG711SsUtilization
          oid: 1.3.6.1.4.1.2879.2.8.5.3.3.1.44
          type: gauge
          help: Percentage utilization of G711SS (silence suppression) resources on this
            server. - 1.3.6.1.4.1.2879.2.8.5.3.3.1.44
          indexes:
          - labelname: sonusSystemDspStatusDspUsageSystemName
            type: DisplayString
        - name: sonusSystemDspStatusDspUsageG711SsTotal
          oid: 1.3.6.1.4.1.2879.2.8.5.3.3.1.43
          type: gauge
          help: Total G711SS (silence suppression) resource capacity on this server. -
            1.3.6.1.4.1.2879.2.8.5.3.3.1.43
          indexes:
          - labelname: sonusSystemDspStatusDspUsageSystemName
            type: DisplayString
        - name: sonusSystemDspStatusDspUsageG711SsUtilization
          oid: 1.3.6.1.4.1.2879.2.8.5.3.3.1.44
          type: gauge
          help: Percentage utilization of G711SS (silence suppression) resources on this
            server. - 1.3.6.1.4.1.2879.2.8.5.3.3.1.44
          indexes:
          - labelname: sonusSystemDspStatusDspUsageSystemName
            type: DisplayString
        - name: sonusAlarmsCurrentStatusDesc
          oid: 1.3.6.1.4.1.2879.2.8.15.1.2.1.3
          type: DisplayString
          help: Description of the alarm. - 1.3.6.1.4.1.2879.2.8.15.1.2.1.3
          indexes:
          - labelname: sonusAlarmsCurrentStatusAlarmId
            type: gauge
        - name: sonusSystemCpuUtilCurrentStatisticsAverage
          oid: 1.3.6.1.4.1.2879.2.8.5.1.17.1.3
          type: gauge
          help: The average cpu % utilization for this interval. - 1.3.6.1.4.1.2879.2.8.5.1.17.1.3
          indexes:
          - labelname: sonusSystemCpuUtilCurrentStatisticsCeName
            type: DisplayString
          - labelname: sonusSystemCpuUtilCurrentStatisticsCpu
            type: gauge
        - name: sonusSystemCpuUtilCurrentStatisticsHigh
          oid: 1.3.6.1.4.1.2879.2.8.5.1.17.1.4
          type: gauge
          help: The high cpu % utilization for this interval. - 1.3.6.1.4.1.2879.2.8.5.1.17.1.4
          indexes:
          - labelname: sonusSystemCpuUtilCurrentStatisticsCeName
            type: DisplayString
          - labelname: sonusSystemCpuUtilCurrentStatisticsCpu
            type: gauge
        - name: sonusSystemCpuUtilCurrentStatisticsLow
          oid: 1.3.6.1.4.1.2879.2.8.5.1.17.1.5
          type: gauge
          help: The low cpu % utilization for this interval. - 1.3.6.1.4.1.2879.2.8.5.1.17.1.5
          indexes:
          - labelname: sonusSystemCpuUtilCurrentStatisticsCeName
            type: DisplayString
          - labelname: sonusSystemCpuUtilCurrentStatisticsCpu
            type: gauge
