{{- if .Values.global.customRbac.create }}
{{- range .Values.global.customRbac.namespaces }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ template "kube-prometheus-stack.fullname" $ }}-prometheus
  namespace: {{ . }}
  labels:
    app: {{ template "kube-prometheus-stack.name" $ }}-prometheus
{{ include "kube-prometheus-stack.labels" $ | indent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ template "kube-prometheus-stack.fullname" $ }}-prometheus
subjects:
  - kind: ServiceAccount
    name: {{ template "kube-prometheus-stack.prometheus.serviceAccountName" $ }}
    namespace: {{ template "kube-prometheus-stack.namespace" $ }}
{{- end }}
{{- end }}
