apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "whatsapp-version-exporter.fullname" . }}
  namespace: {{ include "whatsapp-version-exporter.namespace" . }}
  labels:
    {{- include "whatsapp-version-exporter.labels" . | nindent 4 }}
data:
  config.yaml: |
    namespace: {{ include "whatsapp-version-exporter.namespace" . }}
    whatsapp_versions:
    {{- .Values.config.whatsappVersions | toYaml | nindent 4 }}
