{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "whatsapp-version-exporter.fullname" . }}
  namespace: {{ include "whatsapp-version-exporter.namespace" . }}
  labels:
    {{- include "whatsapp-version-exporter.labels" . | nindent 4 }}
    {{- if .Values.serviceMonitor.additionalLabels }}
{{ toYaml .Values.serviceMonitor.additionalLabels | indent 4 }}
    {{- end }}
  {{- if .Values.serviceMonitor.annotations }}
  annotations:
{{ toYaml .Values.serviceMonitor.annotations | indent 4 }}
  {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "whatsapp-version-exporter.labels" . | nindent 6 }}
  namespaceSelector:
    matchNames:
      - {{ include "whatsapp-version-exporter.namespace" . }}
  endpoints:
    - port: http
      {{- if .Values.serviceMonitor.interval }}
      interval: {{ .Values.serviceMonitor.interval }}
      {{- end }}
      {{- if .Values.serviceMonitor.scrapeTimeout }}
      scrapeTimeout: {{ .Values.serviceMonitor.scrapeTimeout }}
      {{- end }}
      relabelings:
      - sourceLabels: [__meta_kubernetes_pod_label_app_kubernetes_io_name]
        action: replace
        replacement: $1
        regex: (.*)
        targetLabel: app
  {{- end }}

