{{- if .Values.agent.static.deployment.secret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "grafana-agent.fullname" . }}-static-deployment
  labels:
    {{- include "grafana-agent.labels" . | nindent 4 }}
    agent-type: deployment
    mode: static
data:
  {{- range $key, $val := .Values.agent.static.deployment.secret.content }}
  {{ $key }}: {{ $val | b64enc | quote }}
  {{- end }}
{{- end }}
