apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "prometheus-eventhubs-exporter.fullname" . }}
  labels:
    {{- include "prometheus-eventhubs-exporter.labels" . | nindent 4 }}
data:
  eventhubs.properties: |
    {{- .Values.eventhubs.properties | nindent 4 }}
