{{- if .Values.agent.flow.daemonset.enabled }}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "grafana-agent.fullname" . }}-flow-daemonset
  labels:
    {{- include "grafana-agent.labels" . | nindent 4 }}
    agent-type: daemonset
    mode: flow
spec:
  {{- if ge (int .Capabilities.KubeVersion.Minor) 22 }}
  minReadySeconds: 10
  {{- end }}
  selector:
    matchLabels:
      {{- include "grafana-agent.selectorLabels" . | nindent 6 }}
      agent-type: daemonset
      mode: flow
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/flow/daemonset/configmap.yaml") . | sha256sum }}
        {{- if .Values.agent.flow.daemonset.secret.create }}
        checksum/secret: {{ include (print $.Template.BasePath "/flow/daemonset/secret.yaml") . | sha256sum }}
        {{- end }}
      {{- with .Values.agent.common.podAnnotations }}
        {{- toYaml . | nindent 4 }}
      {{- end }}
      labels:
        {{- include "grafana-agent.selectorLabels" . | nindent 8 }}
        agent-type: daemonset
        mode: flow
        {{- with .Values.agent.common.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.global.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "grafana-agent.serviceAccountName" . }}
      {{- if or .Values.global.image.pullSecrets .Values.image.pullSecrets }}
      imagePullSecrets:
        {{- if .Values.global.image.pullSecrets }}
        {{- toYaml .Values.global.image.pullSecrets | nindent 8 }}
        {{- else }}
        {{- toYaml .Values.image.pullSecrets | nindent 8 }}
        {{- end }}
      {{- end }}
      {{- if .Values.agent.flow.daemonset.initContainers }}
      initContainers:
        {{- with .Values.agent.flow.daemonset.initContainers }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- end }}
      containers:
        - name: grafana-agent
          image: {{ .Values.global.image.registry | default .Values.image.registry }}/{{ .Values.image.repository }}{{ include "grafana-agent.imageId" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - run
            - /etc/agent/config.river
            - --storage.path={{ .Values.agent.common.storagePath }}
            - --server.http.listen-addr={{ .Values.agent.common.listenAddr }}:{{ .Values.agent.common.listenPort }}
            {{- if not .Values.agent.common.enableReporting }}
            - --disable-reporting
            {{- end}}
            {{- if .Values.agent.flow.daemonset.clustering.enabled }}
            - --cluster.enabled=true
            - --cluster.join-addresses={{ include "grafana-agent.fullname" . }}-daemonset-cluster
            {{- end}}
            {{- range .Values.agent.flow.daemonset.extraArgs }}
            - {{ . }}
            {{- end}}
          env:
            - name: AGENT_MODE
              value: flow
            - name: HOSTNAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            {{- with .Values.agent.flow.daemonset.extraEnv }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- with .Values.agent.envFrom }}
          envFrom:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          ports:
            - containerPort: {{ .Values.agent.common.listenPort }}
              name: http-metrics
            {{- range $portMap := .Values.agent.extraPorts }}
            - containerPort: {{ $portMap.targetPort }}
              {{- if $portMap.hostPort }}
              hostPort: {{ $portMap.hostPort }}
              {{- end}}
              name: {{ $portMap.name }}
              protocol: {{ coalesce $portMap.protocol "TCP" }}
            {{- end }}
          readinessProbe:
            httpGet:
              path: /-/ready
              port: {{ .Values.agent.common.listenPort }}
              scheme: {{ .Values.agent.common.listenScheme }}
            initialDelaySeconds: 10
            timeoutSeconds: 1
          {{- with .Values.agent.flow.daemonset.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.agent.flow.daemonset.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: config
              mountPath: /etc/agent
            {{- if .Values.agent.flow.daemonset.mounts.varlog }}
            - name: varlog
              mountPath: /var/log
              readOnly: true
            {{- end }}
            {{- if .Values.agent.flow.daemonset.mounts.dockercontainers }}
            - name: dockercontainers
              mountPath: /var/lib/docker/containers
              readOnly: true
            {{- end }}
            {{- if .Values.agent.flow.daemonset.secret.create }}
            - name: secret
              mountPath: /tmp/secret
            {{- end }}
            {{- range .Values.agent.flow.daemonset.mounts.extra }}
            - {{- toYaml . | nindent 14 }}
            {{- end }}
      {{- if .Values.agent.common.priorityClassName }}
      priorityClassName: {{ .Values.agent.common.priorityClassName }}
      {{- end }}
      {{- if .Values.agent.common.hostNetwork }}
      hostNetwork: {{ .Values.agent.common.hostNetwork }}
      {{- end }}
      {{- if .Values.agent.flow.daemonset.hostPID }}
      hostPID: {{ .Values.agent.flow.daemonset.hostPID }}
      {{- end }}
      dnsPolicy: {{ .Values.agent.common.dnsPolicy }}
      {{- with .Values.agent.common.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.agent.flow.daemonset.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.agent.common.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: config
          configMap:
            name: {{ include "grafana-agent.fullname" . }}-flow-daemonset
        {{- if .Values.agent.flow.daemonset.mounts.varlog }}
        - name: varlog
          hostPath:
            path: /var/log
        {{- end }}
        {{- if .Values.agent.flow.daemonset.mounts.dockercontainers }}
        - name: dockercontainers
          hostPath:
            path: /var/lib/docker/containers
        {{- end }}
        {{- if .Values.agent.flow.daemonset.secret.create }}
        - name: secret
          secret:
            secretName: {{ include "grafana-agent.fullname" . }}-flow-daemonset
        {{- end }}
        {{- if .Values.agent.flow.daemonset.volumes.extra }}
        {{- toYaml .Values.agent.flow.daemonset.volumes.extra | nindent 8 }}
        {{- end }}
  {{- with .Values.agent.flow.daemonset.updateStrategy }}
  strategy:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
