apiVersion: v1
kind: Secret
metadata:
  name: {{ include "prometheus-aws-snapshots-checker.fullname" . }}
  labels:
    {{- include "prometheus-aws-snapshots-checker.labels" . | nindent 4 }}
type: Opaque
data:
  AWS_ACCESS_KEY_ID: {{ .Values.aws.secrets.awsAccessKeyId | b64enc | quote }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.aws.secrets.awsSecretAccessKey | b64enc | quote }}
